# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 11:17
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(blank=True, default=1)),
                ('date', models.DateTimeField(default='django.utils.timezone.now')),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta(0, 5400))),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('coming', 'Coming'), ('going', 'Going'), ('ended', 'Ended')], default='Coming', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('file', models.FileField(upload_to='allfiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(default='django.utils.timezone.now')),
                ('file', models.ManyToManyField(related_name='homework_files', to='course.File')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('video', models.FileField(blank=True, upload_to='topics/video/')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='topics/image/')),
                ('level', models.PositiveIntegerField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('files', models.ManyToManyField(related_name='topic_files', to='course.File')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='course.Subject')),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='course.Subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='files',
            field=models.ManyToManyField(related_name='exam_files', to='course.File'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.Subject'),
        ),
    ]
