# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20161014_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
